// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: meal.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createMealWithFoodItems = `-- name: CreateMealWithFoodItems :one
WITH new_meal AS (
  INSERT INTO meals (
      name, 
      description, 
      image_url,
      user_id
    ) 
  VALUES (
      $1, 
      $2, 
      $3,
      $4
    ) 
  RETURNING id, name, description, image_url, created_at, updated_at, user_id
),
inserted_food_items AS (
  INSERT INTO rel_meal_food (
      meal_id, 
      food_item_id, 
      user_id, 
      amount
    ) 
  SELECT 
    new_meal.id, 
    unnest($5::uuid[]), -- unnest to expand array into rows
    $4::uuid,
    unnest($6::numeric[]) -- unnest to expand array into rows
  FROM new_meal
  RETURNING meal_id, food_item_id
)
SELECT 
  m.id AS meal_id,
  m.name,
  m.description,
  m.image_url,
  m.created_at,
  m.updated_at,
  m.user_id,
  json_agg(
    json_build_object(
      'food_item_id', f.food_item_id,
      'name', fi.name,
      'description', fi.description,
      'image_url', fi.image_url,
      'food_type', fi.food_type,
      'calories', fi.calories,
      'fat', fi.fat,
      'protein', fi.protein,
      'carbs', fi.carbs
    )
  ) AS foods
FROM new_meal m
JOIN inserted_food_items f ON f.meal_id = m.id
JOIN food_items fi ON fi.id = f.food_item_id
GROUP BY m.id
`

type CreateMealWithFoodItemsParams struct {
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
	UserID      uuid.UUID
	Column5     []uuid.UUID
	Column6     []string
}

type CreateMealWithFoodItemsRow struct {
	MealID      uuid.UUID
	Name        string
	Description sql.NullString
	ImageUrl    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	UserID      uuid.UUID
	Foods       json.RawMessage
}

func (q *Queries) CreateMealWithFoodItems(ctx context.Context, arg CreateMealWithFoodItemsParams) (CreateMealWithFoodItemsRow, error) {
	row := q.db.QueryRowContext(ctx, createMealWithFoodItems,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.UserID,
		pq.Array(arg.Column5),
		pq.Array(arg.Column6),
	)
	var i CreateMealWithFoodItemsRow
	err := row.Scan(
		&i.MealID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Foods,
	)
	return i, err
}

const getMealsByID = `-- name: GetMealsByID :one
SELECT 
  m.id, m.name, m.description, m.image_url, m.created_at, m.updated_at, m.user_id, 
  COALESCE(SUM(fi.calories * rmf.amount), 0) AS total_calories,
  COALESCE(SUM(fi.fat * rmf.amount), 0) AS total_fat,
  COALESCE(SUM(fi.protein * rmf.amount), 0) AS total_protein,
  COALESCE(SUM(fi.carbs * rmf.amount), 0) AS total_carbs
FROM meals m
LEFT JOIN rel_meal_food rmf ON m.id = rmf.meal_id
LEFT JOIN food_items fi ON rmf.food_item_id = fi.id
WHERE m.id = $1
GROUP BY m.id
`

type GetMealsByIDRow struct {
	ID            uuid.UUID
	Name          string
	Description   sql.NullString
	ImageUrl      sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	UserID        uuid.UUID
	TotalCalories interface{}
	TotalFat      interface{}
	TotalProtein  interface{}
	TotalCarbs    interface{}
}

func (q *Queries) GetMealsByID(ctx context.Context, id uuid.UUID) (GetMealsByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMealsByID, id)
	var i GetMealsByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.TotalCalories,
		&i.TotalFat,
		&i.TotalProtein,
		&i.TotalCarbs,
	)
	return i, err
}
