// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: measurement.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkTodayMeasurement = `-- name: CheckTodayMeasurement :one
SELECT user_id, weight, height, date, created_at, updated_at FROM measurements
WHERE user_id = $1
AND date = CURRENT_DATE
`

func (q *Queries) CheckTodayMeasurement(ctx context.Context, userID uuid.UUID) (Measurement, error) {
	row := q.db.QueryRowContext(ctx, checkTodayMeasurement, userID)
	var i Measurement
	err := row.Scan(
		&i.UserID,
		&i.Weight,
		&i.Height,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeasurementsByUserID = `-- name: GetMeasurementsByUserID :many
SELECT user_id, weight, height, date, created_at, updated_at FROM measurements
WHERE user_id = $1
`

func (q *Queries) GetMeasurementsByUserID(ctx context.Context, userID uuid.UUID) ([]Measurement, error) {
	rows, err := q.db.QueryContext(ctx, getMeasurementsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Measurement
	for rows.Next() {
		var i Measurement
		if err := rows.Scan(
			&i.UserID,
			&i.Weight,
			&i.Height,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
