// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Test struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID           string
	Email        string
	PasswordHash []byte
	Username     string
	ImageUrl     sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
