// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: test.sql

package database

import (
	"context"
)

const createTest = `-- name: CreateTest :one
INSERT INTO tests (name, user_id) VALUES ($1, $2) RETURNING id, user_id, name, created_at, updated_at
`

type CreateTestParams struct {
	Name   string
	UserID string
}

func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (Test, error) {
	row := q.db.QueryRowContext(ctx, createTest, arg.Name, arg.UserID)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
