name: Client CI

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  setup:
    name: Install and Cache Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Fitness-v2-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'

      # Restore node_modules cache before installing dependencies
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: ./Fitness-v2-client/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm 9.0.4
        run: npm install -g pnpm@9.0.4

      - name: Install dependencies
        run: pnpm install

      # Save node_modules to cache after installing dependencies
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./Fitness-v2-client/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  lint:
    name: Run Lint Client (ESLint)
    runs-on: ubuntu-latest
    needs: setup  # Run after the setup job
    defaults:
      run:
        working-directory: ./Fitness-v2-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ESLint
        run: pnpm run lint

  prettier:
    name: Run Prettier Write and Check
    runs-on: ubuntu-latest
    needs: setup  # Run after the setup job
    defaults:
      run:
        working-directory: ./Fitness-v2-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prettier write
        run: pnpm run prettier:write

      - name: Run Prettier check
        run: pnpm run prettier:check

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup  # Run after the setup job
    defaults:
      run:
        working-directory: ./Fitness-v2-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: pnpm run test:ci

  cleanup:
    name: Cleanup After All Jobs
    runs-on: ubuntu-latest
    needs: [lint, prettier, test]  # Cleanup happens after lint, prettier, and test jobs
    steps:
      - name: Perform cleanup
        run: echo "Performing cleanup after all jobs are done"
