name: Client CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Lint Client (ESLint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Fitness-v2-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

  prettier:
    name: Run Prettier Write and Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Fitness-v2-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier write
        run: pnpm run prettier:write

      - name: Run Prettier check
        run: pnpm run prettier:check
