name: Label PR Merged to Staging

on:
  pull_request:
    types: [closed]  # Listen for closed PR events

jobs:
  label:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'  # Only run if the PR is merged into staging
    runs-on: ubuntu-latest
    steps:
      - name: Add label to PR
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels \
          -d '{"labels":["staged"]}'
