name: Server CI

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  setup:
    name: Install and Cache Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Fitness-v2-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.2'

      # Restore Go modules cache before installing dependencies
      - name: Restore Go modules from cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies (Go modules)
      - name: Install dependencies
        run: go mod tidy

      # Save Go modules cache after installing dependencies
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  test:
    name: Run Server Tests
    runs-on: ubuntu-latest
    needs: setup  # Run after the setup job
    defaults:
      run:
        working-directory: ./Fitness-v2-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v ./...

  security:
    name: Run Go Security Check (gosec)
    runs-on: ubuntu-latest
    needs: setup  # Run after the setup job
    defaults:
      run:
        working-directory: ./Fitness-v2-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run security check (gosec)
        run: gosec -exclude-generated ./...

  lint:
    name: Run Go Linting (golangci-lint)
    runs-on: ubuntu-latest
    needs: setup  # Run after the setup job
    defaults:
      run:
        working-directory: ./Fitness-v2-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2

      - name: Run golangci-lint
        run: golangci-lint run ./...
