name: Test Server

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fitness-v2-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      # Run Go tests
      - name: Run tests
        run: go test -v ./...

  security:
    name: Go Security Check (gosec)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fitness-v2-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run security check (gosec)
        run: gosec ./...

  lint:
    name: Go Linting (golangci-lint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fitness-v2-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

      - name: Run golangci-lint
        run: golangci-lint run ./...
